// AUTO-GENERATED by scripts/gen-og-fallbacks.mjs — do not edit by hand.
// Maps each fallback slug to a short sha256 of its PNG bytes; used as
// a ?v= cache-buster on og:image URLs so social scrapers refresh
// when the image changes.
export const OG_FALLBACK_HASHES = {
  "home": "cde39df281",
  "demo": "d544e66ed8",
  "medical": "7885d0fe13",
  "beauty": "4edaa1666c",
  "solar": "e71ee78c81",
  "construction": "484b91507a",
  "real-estate": "3ab402db92"
} as const;
