// AUTO-GENERATED by scripts/gen-og-fallbacks.mjs — do not edit by hand.
// Maps each fallback slug to a short sha256 of its PNG bytes; used as
// a ?v= cache-buster on og:image URLs so social scrapers refresh
// when the image changes.
export const OG_FALLBACK_HASHES = {
  "home": "f2d2d21cdc",
  "demo": "3b509de8d9",
  "medical": "d59bf5be09",
  "beauty": "1a1ba61171",
  "solar": "177aaca70f",
  "construction": "8f59675dac",
  "real-estate": "d3dd9f81c9"
} as const;
