/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SolarRouteImport } from './routes/solar'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as RealEstateRouteImport } from './routes/real-estate'
import { Route as MedicalRouteImport } from './routes/medical'
import { Route as ManifestDotwebmanifestRouteImport } from './routes/manifest[.]webmanifest'
import { Route as FaviconDoticoRouteImport } from './routes/favicon[.]ico'
import { Route as DemoRouteImport } from './routes/demo'
import { Route as ConstructionRouteImport } from './routes/construction'
import { Route as BeautyRouteImport } from './routes/beauty'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DebugHeadRouteImport } from './routes/debug.head'
import { Route as ApiIconFallbackSplatRouteImport } from './routes/api/icon-fallback.$'

const SolarRoute = SolarRouteImport.update({
  id: '/solar',
  path: '/solar',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RealEstateRoute = RealEstateRouteImport.update({
  id: '/real-estate',
  path: '/real-estate',
  getParentRoute: () => rootRouteImport,
} as any)
const MedicalRoute = MedicalRouteImport.update({
  id: '/medical',
  path: '/medical',
  getParentRoute: () => rootRouteImport,
} as any)
const ManifestDotwebmanifestRoute = ManifestDotwebmanifestRouteImport.update({
  id: '/manifest.webmanifest',
  path: '/manifest.webmanifest',
  getParentRoute: () => rootRouteImport,
} as any)
const FaviconDoticoRoute = FaviconDoticoRouteImport.update({
  id: '/favicon.ico',
  path: '/favicon.ico',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoRoute = DemoRouteImport.update({
  id: '/demo',
  path: '/demo',
  getParentRoute: () => rootRouteImport,
} as any)
const ConstructionRoute = ConstructionRouteImport.update({
  id: '/construction',
  path: '/construction',
  getParentRoute: () => rootRouteImport,
} as any)
const BeautyRoute = BeautyRouteImport.update({
  id: '/beauty',
  path: '/beauty',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DebugHeadRoute = DebugHeadRouteImport.update({
  id: '/debug/head',
  path: '/debug/head',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiIconFallbackSplatRoute = ApiIconFallbackSplatRouteImport.update({
  id: '/api/icon-fallback/$',
  path: '/api/icon-fallback/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/beauty': typeof BeautyRoute
  '/construction': typeof ConstructionRoute
  '/demo': typeof DemoRoute
  '/favicon.ico': typeof FaviconDoticoRoute
  '/manifest.webmanifest': typeof ManifestDotwebmanifestRoute
  '/medical': typeof MedicalRoute
  '/real-estate': typeof RealEstateRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/solar': typeof SolarRoute
  '/debug/head': typeof DebugHeadRoute
  '/api/icon-fallback/$': typeof ApiIconFallbackSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/beauty': typeof BeautyRoute
  '/construction': typeof ConstructionRoute
  '/demo': typeof DemoRoute
  '/favicon.ico': typeof FaviconDoticoRoute
  '/manifest.webmanifest': typeof ManifestDotwebmanifestRoute
  '/medical': typeof MedicalRoute
  '/real-estate': typeof RealEstateRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/solar': typeof SolarRoute
  '/debug/head': typeof DebugHeadRoute
  '/api/icon-fallback/$': typeof ApiIconFallbackSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/beauty': typeof BeautyRoute
  '/construction': typeof ConstructionRoute
  '/demo': typeof DemoRoute
  '/favicon.ico': typeof FaviconDoticoRoute
  '/manifest.webmanifest': typeof ManifestDotwebmanifestRoute
  '/medical': typeof MedicalRoute
  '/real-estate': typeof RealEstateRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/solar': typeof SolarRoute
  '/debug/head': typeof DebugHeadRoute
  '/api/icon-fallback/$': typeof ApiIconFallbackSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/beauty'
    | '/construction'
    | '/demo'
    | '/favicon.ico'
    | '/manifest.webmanifest'
    | '/medical'
    | '/real-estate'
    | '/sitemap.xml'
    | '/solar'
    | '/debug/head'
    | '/api/icon-fallback/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/beauty'
    | '/construction'
    | '/demo'
    | '/favicon.ico'
    | '/manifest.webmanifest'
    | '/medical'
    | '/real-estate'
    | '/sitemap.xml'
    | '/solar'
    | '/debug/head'
    | '/api/icon-fallback/$'
  id:
    | '__root__'
    | '/'
    | '/beauty'
    | '/construction'
    | '/demo'
    | '/favicon.ico'
    | '/manifest.webmanifest'
    | '/medical'
    | '/real-estate'
    | '/sitemap.xml'
    | '/solar'
    | '/debug/head'
    | '/api/icon-fallback/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BeautyRoute: typeof BeautyRoute
  ConstructionRoute: typeof ConstructionRoute
  DemoRoute: typeof DemoRoute
  FaviconDoticoRoute: typeof FaviconDoticoRoute
  ManifestDotwebmanifestRoute: typeof ManifestDotwebmanifestRoute
  MedicalRoute: typeof MedicalRoute
  RealEstateRoute: typeof RealEstateRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SolarRoute: typeof SolarRoute
  DebugHeadRoute: typeof DebugHeadRoute
  ApiIconFallbackSplatRoute: typeof ApiIconFallbackSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/solar': {
      id: '/solar'
      path: '/solar'
      fullPath: '/solar'
      preLoaderRoute: typeof SolarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/real-estate': {
      id: '/real-estate'
      path: '/real-estate'
      fullPath: '/real-estate'
      preLoaderRoute: typeof RealEstateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/medical': {
      id: '/medical'
      path: '/medical'
      fullPath: '/medical'
      preLoaderRoute: typeof MedicalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manifest.webmanifest': {
      id: '/manifest.webmanifest'
      path: '/manifest.webmanifest'
      fullPath: '/manifest.webmanifest'
      preLoaderRoute: typeof ManifestDotwebmanifestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favicon.ico': {
      id: '/favicon.ico'
      path: '/favicon.ico'
      fullPath: '/favicon.ico'
      preLoaderRoute: typeof FaviconDoticoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo': {
      id: '/demo'
      path: '/demo'
      fullPath: '/demo'
      preLoaderRoute: typeof DemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/construction': {
      id: '/construction'
      path: '/construction'
      fullPath: '/construction'
      preLoaderRoute: typeof ConstructionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/beauty': {
      id: '/beauty'
      path: '/beauty'
      fullPath: '/beauty'
      preLoaderRoute: typeof BeautyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/debug/head': {
      id: '/debug/head'
      path: '/debug/head'
      fullPath: '/debug/head'
      preLoaderRoute: typeof DebugHeadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/icon-fallback/$': {
      id: '/api/icon-fallback/$'
      path: '/api/icon-fallback/$'
      fullPath: '/api/icon-fallback/$'
      preLoaderRoute: typeof ApiIconFallbackSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BeautyRoute: BeautyRoute,
  ConstructionRoute: ConstructionRoute,
  DemoRoute: DemoRoute,
  FaviconDoticoRoute: FaviconDoticoRoute,
  ManifestDotwebmanifestRoute: ManifestDotwebmanifestRoute,
  MedicalRoute: MedicalRoute,
  RealEstateRoute: RealEstateRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SolarRoute: SolarRoute,
  DebugHeadRoute: DebugHeadRoute,
  ApiIconFallbackSplatRoute: ApiIconFallbackSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
