/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ManifestDotwebmanifestRouteImport } from './routes/manifest[.]webmanifest'
import { Route as FaviconDoticoRouteImport } from './routes/favicon[.]ico'
import { Route as ConstructionRouteImport } from './routes/construction'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiIconFallbackSplatRouteImport } from './routes/api/icon-fallback.$'

const ManifestDotwebmanifestRoute = ManifestDotwebmanifestRouteImport.update({
  id: '/manifest.webmanifest',
  path: '/manifest.webmanifest',
  getParentRoute: () => rootRouteImport,
} as any)
const FaviconDoticoRoute = FaviconDoticoRouteImport.update({
  id: '/favicon.ico',
  path: '/favicon.ico',
  getParentRoute: () => rootRouteImport,
} as any)
const ConstructionRoute = ConstructionRouteImport.update({
  id: '/construction',
  path: '/construction',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiIconFallbackSplatRoute = ApiIconFallbackSplatRouteImport.update({
  id: '/api/icon-fallback/$',
  path: '/api/icon-fallback/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/construction': typeof ConstructionRoute
  '/favicon.ico': typeof FaviconDoticoRoute
  '/manifest.webmanifest': typeof ManifestDotwebmanifestRoute
  '/api/icon-fallback/$': typeof ApiIconFallbackSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/construction': typeof ConstructionRoute
  '/favicon.ico': typeof FaviconDoticoRoute
  '/manifest.webmanifest': typeof ManifestDotwebmanifestRoute
  '/api/icon-fallback/$': typeof ApiIconFallbackSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/construction': typeof ConstructionRoute
  '/favicon.ico': typeof FaviconDoticoRoute
  '/manifest.webmanifest': typeof ManifestDotwebmanifestRoute
  '/api/icon-fallback/$': typeof ApiIconFallbackSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/construction'
    | '/favicon.ico'
    | '/manifest.webmanifest'
    | '/api/icon-fallback/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/construction'
    | '/favicon.ico'
    | '/manifest.webmanifest'
    | '/api/icon-fallback/$'
  id:
    | '__root__'
    | '/'
    | '/construction'
    | '/favicon.ico'
    | '/manifest.webmanifest'
    | '/api/icon-fallback/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ConstructionRoute: typeof ConstructionRoute
  FaviconDoticoRoute: typeof FaviconDoticoRoute
  ManifestDotwebmanifestRoute: typeof ManifestDotwebmanifestRoute
  ApiIconFallbackSplatRoute: typeof ApiIconFallbackSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/manifest.webmanifest': {
      id: '/manifest.webmanifest'
      path: '/manifest.webmanifest'
      fullPath: '/manifest.webmanifest'
      preLoaderRoute: typeof ManifestDotwebmanifestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favicon.ico': {
      id: '/favicon.ico'
      path: '/favicon.ico'
      fullPath: '/favicon.ico'
      preLoaderRoute: typeof FaviconDoticoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/construction': {
      id: '/construction'
      path: '/construction'
      fullPath: '/construction'
      preLoaderRoute: typeof ConstructionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/icon-fallback/$': {
      id: '/api/icon-fallback/$'
      path: '/api/icon-fallback/$'
      fullPath: '/api/icon-fallback/$'
      preLoaderRoute: typeof ApiIconFallbackSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ConstructionRoute: ConstructionRoute,
  FaviconDoticoRoute: FaviconDoticoRoute,
  ManifestDotwebmanifestRoute: ManifestDotwebmanifestRoute,
  ApiIconFallbackSplatRoute: ApiIconFallbackSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
